apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: postgresql
    version: 10.4.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enableDependency
    tags:
      - database
